MartianRation/Controllers/RationController.cs
using MartianRation.Code.Repository;
using MartianRation.Data.Edmx;
using MartianRation.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MartianRation.Controllers
{
    public class RationController : Controller
    {
        // GET: Ration
        //public ActionResult Index()
        //{
        //    return View();
        //}

        private IGenericService<PacketRation> _packetRationService = null;
        private IGenericService<PacketType> _packetTypeService = null;

        /// <summary>
        /// RationController  non-parameterized  Constructor.
        /// it is used to initialize  Generic repository class object.
        /// </summary>
        public RationController()
        {
            this._packetRationService = new GenericService<Data.Edmx.PacketRation>();
            this._packetTypeService = new GenericService<PacketType>();
        }

        /// <summary>
        ///RationController Parameterized Constructor contains Generic class type parameter.       
        /// </summary>
        public RationController(IGenericService<PacketRation> packetRationService, IGenericService<PacketType> packetTypeService)
        {
            this._packetRationService = packetRationService;
            this._packetTypeService = packetTypeService;
        }

        /// <summary>
        ///Packet Ration Defualt Action Method
        /// </summary>
        [HttpGet]
        public ActionResult PacketRation()
        {
            return View();
        }

        /// <summary>
        ///  Get Packet Ration from database and view on view page. 
        ///  GetData Action Method calling from Ajax calling.
        ///  This method return PaketRationModel list in the json.
        /// </summary>
        [HttpGet]
        public ActionResult GetData()
        {
            List<PacketRationModel> mdllist = new List<PacketRationModel>();
            try
            {
                var packetrationlist = _packetRationService.GetAll();
                foreach (var item in packetrationlist)
                {
                    PacketRationModel packetrationmodel = new PacketRationModel();
                    packetrationmodel.PacketId = item.PacketId;
                    packetrationmodel.PacketContent = item.PacketContent;
                    packetrationmodel.Quantity = item.Quantity;

                    packetrationmodel.PacketTypeName = item.PacketTypeId == 1 ? "Food" : "Water";
                    packetrationmodel.ExpiryDate = item.ExpiryDate == null ? "-" : item.ExpiryDate.Value.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
                    packetrationmodel.PacketTypeCode = item.PacketTypeId == 1 ? "F" + item.PacketId : "W" + item.PacketId;
                    packetrationmodel.PacketContent = item.PacketContent == null ? "-" : item.PacketContent;
                    packetrationmodel.QuantityType = item.Quantity == null ? "-" : Convert.ToString(item.Quantity);
                    packetrationmodel.CaloriesContent = item.Calories == null ? "-" : Convert.ToString(item.Calories);
                    packetrationmodel.Calories = item.Calories;

                    mdllist.Add(packetrationmodel);
                }

                mdllist.ToList().OrderBy(x => x.PacketId);

            }
            catch (Exception ex)
            {
            };
            return Json(new { data = mdllist.ToList() }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save  Action Method used to  Get Packet Ration from database and showing on view page.
        ///  This Action Method used to in both case save and edit functionality.
        ///  In the case of save id parameter value is zero and in case of edit id parameter value is selected paketrationid.
        ///  In case of Save it is return PaketType list by model, in case of edit it is return selected paketration info by model.
        /// </summary>
        [HttpGet]
        public ActionResult Save(int id)
        {
            PacketRationModel packetrationmodel = new PacketRationModel();
            try
            {
                if (id > 0)
                {
                    var result = _packetRationService.GetById(id);
                    if (result != null)
                    {
                        packetrationmodel.PacketId = result.PacketId;
                        packetrationmodel.PacketTypeId = result.PacketTypeId;
                        packetrationmodel.PacketTypeName = result.PacketTypeId == 1 ? "Food" : "Water";
                        packetrationmodel.PacketContent = result.PacketContent;
                        packetrationmodel.Calories = result.Calories;
                        if (result.ExpiryDate != null)
                        {
                            packetrationmodel.ExpiryDate = result.ExpiryDate.Value.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
                        }
                        packetrationmodel.Quantity = result.Quantity;
                        var packettypelist = _packetTypeService.GetAll();
                        packetrationmodel.PacketTypeList = new SelectList(packettypelist, "PacketTypeId", "PacketNameType", result.PacketTypeId);
                    }
                }
                else
                {
                    int selectedId = 0;
                    var packettypelist = _packetTypeService.GetAll();
                    packetrationmodel.PacketTypeList = new SelectList(packettypelist, "PacketTypeId", "PacketNameType", selectedId);
                }

            }
            catch (Exception ex)
            {
            }
            return View(packetrationmodel);
        }

        /// <summary>
        /// This Post Action Method used to save Packet Ration info into database 
        /// in the both case adding new record and update edited record.        
        /// </summary>
        [HttpPost]
        public ActionResult Save(PacketRationModel model)
        {
            bool status = false;
            try
            {
                if (model.PacketTypeId != null)
                {
                    if (model.PacketTypeId == 1 && model.ExpiryDate != null)
                    {
                        ModelState.Remove("Quantity");
                    }
                    else if (model.PacketTypeId == 2 && model.ExpiryDate == null)
                    {
                        ModelState.Remove("ExpiryDate");
                        ModelState.Remove("Calories");
                    }
                }

                if (ModelState.IsValid)
                {
                    if (model.PacketId > 0)
                    {
                        //Edit
                        var res = _packetRationService.GetById(model.PacketId);
                        if (res != null)
                        {
                            res.PacketId = model.PacketId;
                            res.PacketContent = model.PacketContent;
                            res.Calories = model.Calories;
                            if (model.ExpiryDate != null && model.ExpiryDate != "")
                            {
                                DateTime dtDate = DateTime.ParseExact(model.ExpiryDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                                res.ExpiryDate = dtDate;
                                //string strDate = dtDate.ToString("yyyy-MM-dd");
                                //res.ExpiryDate = Convert.ToDateTime(strDate);
                            }
                            else
                            {
                                res.ExpiryDate = null;
                            }

                            res.Quantity = model.Quantity;
                            _packetRationService.Update(res);
                        }

                    }
                    else
                    {
                        //Save
                        PacketRation tab = new PacketRation();
                        tab.PacketTypeId = model.PacketTypeId;
                        tab.PacketContent = model.PacketContent;
                        tab.Calories = model.Calories;
                        if (model.ExpiryDate != null && model.ExpiryDate != "")
                        {
                            DateTime dtDate = DateTime.ParseExact(model.ExpiryDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                            tab.ExpiryDate = dtDate;
                            //string strDate = dtDate.ToString("yyyy-MM-dd");                            
                            //tab.ExpiryDate = Convert.ToDateTime(strDate);
                        }

                        tab.Quantity = model.Quantity;

                        _packetRationService.Insert(tab);

                    }
                    _packetRationService.Save();
                    status = true;
                }
            }
            catch (Exception ex)
            {
            }
            return new JsonResult { Data = new { status = status } };
        }

        /// <summary>
        ///  Get Packet Ration selected info from database  for deletion.
        ///  This action method only one parameter integer id by this id get information from database.
        ///  This action method return info in the PacketRationModel and view on the deleting popup.       
        /// </summary>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            PacketRationModel model = new PacketRationModel();
            try
            {
                var res = _packetRationService.GetById(id);
                if (res != null)
                {
                    var packetname = _packetTypeService.GetById(res.PacketTypeId).PacketNameType;
                    model.PacketId = res.PacketId;
                    model.PacketTypeId = res.PacketTypeId;

MartianRation/Views/Ration/Delete.cshtml
@model MartianRation.Models.PacketRationModel
@{
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm("Delete", "Ration", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(m=>m.PacketId)  

    <div class="form-group">
        <label>Packet Type</label>
        <p>@Model.PacketTypeName</p>      
    </div>

    <div class="form-group">
        <label>Packet Content</label>
        <p>@Model.PacketContent</p>
    </div>

    <div class="form-group">
        <label>Quantity</label>
        <p>@Model.Quantity</p>
    </div>

    <div class="form-group">
        <label>Expiry Date</label>
        <p>@Model.ExpiryDate</p>
    </div>

    <div class="form-group">
        <label>Calories</label>
        <p>@Model.Calories</p>
    </div>

    <div>
        <input type="submit" value="Delete" class="btn btn-danger"/>
    </div>
}

MartianRation/Views/Ration/PacketRation.cshtml
<script src="~/Scripts/JS/js/jquery-3.1.1.min.js"></script>
<style type="text/css">
    .ui-dialog-titlebar-close {
        background-image: url('../../Content/Images/close.png');
    }

    .btnCustom {
        padding: 0px 12px !important;
        border-radius:25px !important;
    }
</style>
<div style="width:90%; margin:0 auto;" class="tablecontainer">
    <a class="popup btn btn-primary" href="/Ration/Save/0" style="margin-bottom:20px; margin-top:20px;">Add Ration</a>
    <table id="myDatatable" class="table table-bordered">
        <thead>
            <tr style="background:gray;color:white;">
                <th style="visibility:hidden">Packet Id</th>
                <th>Packet Id</th>
                <th>Packet Type</th>
                <th>Packet Content</th>
                <th>Calories</th>
                <th>Expiry Date</th>
                <th>Quantity</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
    </table>
</div>
<script type="text/javascript">

    $(document).ready(function () {

        var oTable = $("#myDatatable").DataTable({

            "ajax": {
                "url": "/Ration/GetData",
                "type": "get",
                "datatype": "json"
            },
            "columns": [
                { "data": "PacketId", "autoWidth": true, "visible": false },
                { "data": "PacketTypeCode", "autoWidth": true, "className": "text-center"},
                { "data": "PacketTypeName", "autoWidth": true, "className": "text-center"},
                { "data": "PacketContent", "autoWidth": true, "className": "text-center"},
                { "data": "CaloriesContent", "autoWidth": true, "className": "text-center"},
                {
                    "data": "ExpiryDate", "autoWidth": true, "className": "text-center"

                },
                { "data": "QuantityType", "autoWidth": true, "className": "text-center" },
                {
                    "data": "PacketId", "width": "50px", "render": function (data) {

                        return '<a class="popup btnCustom btn-primary" href="/Ration/Save/' + data + '">Edit</a>';
                    }
                },
                {
                    "data": "PacketId", "width": "50px", "render": function (data) {
                        return '<a class="popup btnCustom btn-danger" href="/Ration/Delete/' + data + '">Delete</a>';
                    }
                }
            ]
        });
        $('.tablecontainer').on('click', 'a.popup', function (e) {
            e.preventDefault();
            OpenPopup($(this).attr('href'));
        })
        function OpenPopup(pageUrl) {
            var $pageContent = $('<div/>');
            $pageContent.load(pageUrl, function () {
                $('#popupForm', $pageContent).removeData('validator');
                $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                $.validator.unobtrusive.parse('form');

            });

            $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                .html($pageContent)
                .dialog({
                    draggable: false,
                    autoOpen: false,
                    resizable: false,
                    model: true,
                    title: 'Popup',
                    height: 550,
                    width: 600,
                    close: function () {
                        $dialog.dialog('destroy').remove();
                    }
                })

            $('.popupWindow').on('submit', '#popupForm', function (e) {
                var url = $('#popupForm')[0].action;
                $.ajax({
                    type: "POST",
                    url: url,
                    data: $('#popupForm').serialize(),
                    success: function (data) {
                        if (data.status) {
                            $dialog.dialog('close');
                            oTable.ajax.reload();
                        }
                    }
                })

                e.preventDefault();
            })

            $dialog.dialog('open');
        }
    });


</script>

MartianRation/Views/Ration/Save.cshtml
@model MartianRation.Models.PacketRationModel


@{
    Layout = null;
    ViewBag.Title = "Save";
}
<link href="~/Scripts/DatePicker/bootstrap-datepicker.css" rel="stylesheet" />
<script src="~/Scripts/DatePicker/bootstrap-datepicker.js"></script>

@using (Html.BeginForm("Save", "Ration", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.PacketId > 0)
    {
        @Html.HiddenFor(a => a.PacketId)
        @Html.HiddenFor(a => a.PacketTypeId)
    }

    <div class="form-group">
        @Html.LabelFor(model => model.PacketTypeId, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.PacketTypeId, Model.PacketTypeList, "Select PacketType", new { @id = "ddlPacketTypeId", @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PacketTypeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PacketContent, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.PacketContent, new { htmlAttributes = new { @id = "txtPacketContent", @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.PacketContent, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @id = "txtCalories", @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control datepicker", @id = "datepicker", @autocomplete = "off"} })
        @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @id = "txtQuantity", @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
    </div>

    <div>
        <input type="submit" value="Save" class="btn btn-primary"/>
    </div>
}

<script>
    var date = new Date();
    date.setDate(date.getDate());
    $('#datepicker').datepicker({
        changeMonth: true,
        changeYear: true,
        format: "dd/mm/yyyy",
        language: "en-US",
        //language: "tr",
        startDate: date
    });

    $(function () {
        $('#ddlPacketTypeId').on('change', function (e) {
            var ddlPacketTypeId = $(this).val();
            //1=food, 2=water
            if (ddlPacketTypeId == 1) {
                // for disable.....
                $("#txtQuantity").prop("readonly", true);
                $("#txtCalories").prop("readonly", false);
                //$("#datepicker").prop("readonly", false);
                $("#datepicker").prop("readonly", false);
                //for remove or add validation...
                $('#txtQuantity').rules('remove', 'required');
                $('#txtCalories').rules('add', 'required');
                $('#datepicker').rules('add', 'required');
            }
            else if (ddlPacketTypeId == 2) {
                //for remove validation...
                $('#txtQuantity').rules('add', 'required');
                $('#txtCalories').rules('remove', 'required');
                $('#datepicker').rules('remove', 'required');
                // for disable.....
                $("#txtCalories").prop("readonly", true);
                $("#datepicker").prop("readonly", true);
                $("#txtQuantity").prop("readonly", false);
            }
            else if (ddlPacketTypeId == "") {
                //for add validation...
                $('#txtQuantity').rules('add', 'required');
                $('#txtCalories').rules('add', 'required');
                $('#datepicker').rules('add', 'required');
                //enable controls
                $("#txtCalories").prop("readonly", false);
                $("#datepicker").prop("readonly", false);
                $("#txtQuantity").prop("readonly", false);

            }
        });
    });

    $("document").ready(function () {
        var chkPacketId = '@Model.PacketId';
        var chkPacketTypeId = '@Model.PacketTypeId';
        if (chkPacketId > 0)
        {
            $("#ddlPacketTypeId").attr("disabled", "disabled");
            if (chkPacketTypeId == 1)
            {
                // for disable.....
                $("#txtQuantity").prop("readonly", true);
                $("#txtCalories").prop("readonly", false);
                //$("#datepicker").prop("readonly", false);
                $("#datepicker").prop("readonly", false);
                //for remove or add validation...
                $('#txtQuantity').rules('remove', 'required');
                $('#txtCalories').rules('add', 'required');
                $('#datepicker').rules('add', 'required');
            }
            else if (chkPacketTypeId == 2)
            {
                //for remove validation...
                $('#txtQuantity').rules('add', 'required');
                $('#txtCalories').rules('remove', 'required');
                $('#datepicker').rules('remove', 'required');
                // for disable.....
                $("#txtCalories").prop("readonly", true);
                $("#datepicker").prop("readonly", true);
                $("#txtQuantity").prop("readonly", false);
            }
        }
     });
</script>