MartianRation/Controllers/ViewScheduleController.cs
using MartianRation.Code.Repository;
using MartianRation.Data.Edmx;
using MartianRation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MartianRation.Controllers
{
    public class ViewScheduleController : Controller
    {
        private MartianRationDBEntities _context = new MartianRationDBEntities();
        private IGenericService<PacketRation> _packetRationService = null;
        private IGenericService<PacketType> _packetTypeService = null;

        /// <summary>
        ///ViewScheduleController non-parameterized Constructor       
        /// it is used to initialize  Generic repository class object.
        /// </summary>
        public ViewScheduleController()
        {
            this._packetRationService = new GenericService<PacketRation>();
            this._packetTypeService = new GenericService<PacketType>();
        }

        /// <summary>
        ///ViewScheduleController Parameterized Constructor pass two generic class type parameters.        
        /// </summary>
        public ViewScheduleController(IGenericService<PacketRation> packetRationService, IGenericService<PacketType> packetTypeService)
        {
            this._packetRationService = packetRationService;
            this._packetTypeService = packetTypeService;
        }

        /// <summary>
        ///Get action method to showing ViewScheduler page.
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            PacketRationResult model = new PacketRationResult();
            return View(model);
        }

        /// <summary>
        ///Post action method to showing Scheduler records on  ViewScheduler page.
        ///In this method pass one parameter selected date as string.
        ///
        /// </summary>
        [HttpPost]
        public ActionResult Index(string selectedDate)
        {
            if(string.IsNullOrEmpty(selectedDate))
            {
                return RedirectToAction("Index");
            }
            DateTime startDate = DateTime.ParseExact(selectedDate, "dd/MM/yyyy", null);
            PacketRationResult model = new PacketRationResult();
            try
            {
                var result = _context.getViewSchedule(startDate).OrderBy(x => x.ScheduleDate).ToList();
                var chkcount = result.GroupBy(x => x.ScheduleDate).Select(x => x.First()).ToList().Count();

                if(result.Count > 0)
                {
                    model.ScheduleCount = chkcount;

                    foreach (var item in result)
                    {
                        int PacketTypeId = Convert.ToInt32(item.PacketTypeId);
                        PacketRationResult packetRation = new PacketRationResult();
                        packetRation.PacketId = item.PacketId;
                        packetRation.PacketTypeId = item.PacketTypeId;
                        packetRation.PacketTypeName = _packetTypeService.GetById(PacketTypeId).PacketNameType;
                        packetRation.PacketContent = item.PacketContent != null ? item.PacketContent : "-";
                        packetRation.Calories = item.Calories;
                        packetRation.ExpiryDate = item.ExpiryDate != null ? item.ExpiryDate : null;
                        packetRation.StrExpiryDate = item.ExpiryDate == null ? "-" : Convert.ToDateTime(item.ExpiryDate.ToString()).ToString("dd/MM/yyyy");
                        packetRation.Quantity = item.Quantity;
                        packetRation.StrScheduleDate = Convert.ToDateTime(item.ScheduleDate.ToString()).ToString("dd/MM/yyyy");
                        packetRation.QuantityText = item.QuantityText;

                        model.datalist.Add(packetRation);
                    }
                }                            
            }
            catch (Exception ex)
            {
            }
            return View(model);
        }
    }
}

MartianRation/Views/ViewSchedule/Index.cshtml
@model MartianRation.Models.PacketRationResult
@{
    ViewBag.Title = "Index";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <br />
        @using (Html.BeginForm("Index", "ViewSchedule", FormMethod.Post, new { id = "Form" }))
        {
            <div class="row col-md-12">
                <div class="form-group">
                    <div class="row col-md-4">
                        Start Date:
                        @Html.TextBox("SelectedDate", "", new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" })
                    </div>
                    <div class="row col-md-2" style='float:left;'>
                        <br />
                        <input type="submit" value="View Schedule" id="btnViewSchedule" class="btn btn-primary" />
                    </div>
                </div>
            </div>



            if (Model.datalist.Count() > 0)
            {
                <table id="myTable" class="table table-bordered">
                    <caption></caption>
                    <colgroup span=3></colgroup>
                    <thead>
                        <tr style="background:gray;color:white;">
                            <th style="text-align:center">Schedule Date</th>
                            <th style="text-align:center">Packet Id</th>
                            <th style="text-align:center">Packet Type</th>
                            <th style="text-align:center">Packet Content</th>
                            <th style="text-align:center">Calories</th>
                            <th style="text-align:center">ExpiryDate</th>
                            <th style="text-align:center">Quantity</th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.datalist)
                    {
                        <tr>
                            <td style="text-align:center">@item.StrScheduleDate</td>
                            <td style="text-align:center">@item.QuantityText</td>
                            <td style="text-align:center">@item.PacketTypeName</td>
                            <td style="text-align:center">@item.PacketContent</td>
                            <td style="text-align:center">@item.Calories</td>
                            <td style="text-align:center">@item.StrExpiryDate</td>
                            <td style="text-align:center">@item.Quantity</td>

                        </tr>
                    }
                </table>

                <div><p style="font-weight:bold"> Number of days you can survive with current inventory : @Model.ScheduleCount</p> </div>
            }            
        }

        <!-- Bootstrap -->
        <script src="~/Scripts/JS/jquery_1.8.3/jquery-1.8.3.min.js"></script>
        <link href="~/Scripts/DatePicker/bootstrap-datepicker.css" rel="stylesheet" />
        <script src="~/Scripts/DatePicker/bootstrap-datepicker.js"></script>
        <script>
            var date = new Date();
            date.setDate(date.getDate());
            $('#SelectedDate').datepicker({
                changeMonth: true,
                changeYear: true,
                format: "dd/mm/yyyy",
                language: "en-US",
                //language: "tr",
                startDate: date
            });
        </script>
        <script>
            $(function () {
                function groupTable($rows, startIndex, total) {
                    if (total === 0) {
                        return;
                    }

                    var i, currentIndex = startIndex, count = 1, lst = [];
                    var tds = $rows.find('td:eq(' + currentIndex + ')');
                    var ctrl = $(tds[0]);
                    lst.push($rows[0]);
                    for (i = 1; i <= tds.length; i++) {
                        if (ctrl.text() == $(tds[i]).text()) {
                            count++;
                            $(tds[i]).addClass('deleted');
                            lst.push($rows[i]);
                        }
                        else {
                            if (count > 1) {
                                ctrl.attr('rowspan', count);
                                groupTable($(lst), startIndex + 1, total - 1)
                            }
                            count = 1;
                            lst = [];
                            ctrl = $(tds[i]);
                            lst.push($rows[i]);
                        }

                    }

                }
                groupTable($('#myTable tr:has(td)'), 0, 1);
                $('#myTable .deleted').remove();
            });
        </script>
</body>
</html>